

version: '3.3'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - 'postgres:/var/lib/postgresql/data'
      - './sql/init.sql:/docker-entrypoint-initdb.d/init.sql'
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: soso_user
      POSTGRES_DB: soso_dev

volumes:
  postgres: